### PR TITLE
Enable IPv6

### PR DESCRIPTION
**Pull request by burdandrei**
It's 2017 =)

### CODE REVIEW

**Comment by kung-foo** [comment]
yes it is.

do you know the minimum tf version for these new provider features?

**Comment by kung-foo** [comment]
When I run a plan (using terraform 0.9.5) I get this:

```
$ AWS_PROFILE=personal terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.default: Refreshing state...
data.aws_ami.default: Refreshing state...
data.aws_route53_zone.default: Refreshing state...
data.aws_ami.default: Refreshing state...
Error running plan: 2 error(s) occurred:

* module.cdn-us-east-2.aws_route53_record.cdnv6: 1 error(s) occurred:

* module.cdn-us-east-2.aws_route53_record.cdnv6: Resource 'aws_instance.server' does not have attribute 'ipv6_addresses.0' for variable 'aws_instance.server.*.ipv6_addresses.0'
* module.cdn-us-east-1.aws_route53_record.cdnv6: 1 error(s) occurred:

* module.cdn-us-east-1.aws_route53_record.cdnv6: Resource 'aws_instance.server' does not have attribute 'ipv6_addresses.0' for variable 'aws_instance.server.*.ipv6_addresses.0'
```

**Comment by burdandrei** [comment]
i just checked the changelog, and it looks like ipv6 supported started to be included in ~ 0.8.8
I planned, applied and destoyed my code on 0.9.2, and you are right, it's not working on 0.9.5.
checking how can i fix it

**Comment by burdandrei** [comment]
OK, on a clean run it fails on 0.9.2 too.
when i developed it, i added ipv6 all over the stack, and then worked on route53.
problem is that in the begining, there is no object for ipv6_address, only for ipv6_address_count:
```
+ module.cdn-eu-west-1.aws_instance.server.0
    ami:                         "ami-cfeeb3a9"
    associate_public_ip_address: "<computed>"
    availability_zone:           "<computed>"
    ebs_block_device.#:          "<computed>"
    ephemeral_block_device.#:    "<computed>"
    instance_state:              "<computed>"
    instance_type:               "t2.nano"
    ipv6_address_count:          "1"
    ipv6_addresses.#:            "<computed>"
    key_name:                    "<computed>"
    network_interface_id:        "<computed>"
    placement_group:             "<computed>"
    private_dns:                 "<computed>"
    private_ip:                  "<computed>"
    public_dns:                  "<computed>"
    public_ip:                   "<computed>"
    root_block_device.#:         "<computed>"
    security_groups.#:           "<computed>"
    source_dest_check:           "true"
    subnet_id:                   "${element(aws_subnet.public.*.id, count.index)}"
    tags.%:                      "1"
    tags.Name:                   "cdn-server-eu-west-1a-0"
    tenancy:                     "<computed>"
    vpc_security_group_ids.#:    "<computed>"
```

i have to think how to jack it around.
if you'll got any ideas, please share. =)

**Comment by burdandrei** [comment]
Ok, i made the thing that you commented out to work (aws_availabilty zones),
but because https://github.com/hashicorp/terraform/issues/8696 i got a problem adding ipv6. will think about it a bit more

**Comment by kung-foo** [comment]
we should try again now that https://github.com/hashicorp/terraform/pull/15278 has been merged into master

**Comment by burdandrei** [comment]
Oh, cool, but I'm on vacation for a couple of weeks. Will get back to it in September. Thanks for the heads up!

**Comment by kung-foo** [comment]
Everything is working now with the new `flatten` function. Thanks for the PR!

**Comment by burdandrei** [comment]
thanks for finishing it up!

**Pull request merged**
